### ISSUE TITLE
请帮忙看看，运行到这里报错了

### ISSUE THREAD

**Issue by kelnic88** [tianyu211/DealGooglePhotosArchive#1]
根据时长分类文件：G:/takeout-2021/Takeout\Google 相册\Photos from 2021\IMG_2051.MOV
Traceback (most recent call last):
  File "D:\GooglePhotos\DealGooglePhotosArchive.py", line 149, in <module>
    dealExif()
  File "D:\GooglePhotos\DealGooglePhotosArchive.py", line 106, in dealExif
    exifJson = readJson(scanDir + '/json/' + file_name + '.json')
  File "D:\GooglePhotos\DealGooglePhotosArchive.py", line 92, in readJson
    return json.load(load_f)
  File "C:\Users\KKKK\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb4 in position 170: illegal multibyte sequence

**Comment by Yuuuu9658** [comment]
试着把第`94`行的
```
with open(json_file, 'r') as load_f:
```
改为
```
with open(json_file, 'r',encoding='UTF-8') as load_f:
```
再运行看看

**Comment by kelnic88** [comment]
接着的问题

处理Exif：G:/takeout-2021/Takeout\GooglePhotos\Photos from 2020\IMG_0234.JPG
处理Exif：G:/takeout-2021/Takeout\GooglePhotos\Photos from 2020\IMG_0235.JPG
Traceback (most recent call last):
  File "C:\Users\KKKK\AppData\Local\Programs\Python\Python310\lib\site-packages\piexif\_dump.py", line 272, in _value_to_bytes
    value_str = raw_value + b"\x00" * (4 - length)
TypeError: can only concatenate tuple (not "bytes") to tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KKKK\AppData\Local\Programs\Python\Python310\lib\site-packages\piexif\_dump.py", line 335, in _dict_to_bytes
    length_str, value_str, four_bytes_over = _value_to_bytes(raw_value,
  File "C:\Users\KKKK\AppData\Local\Programs\Python\Python310\lib\site-packages\piexif\_dump.py", line 274, in _value_to_bytes
    raise ValueError("Got invalid type to convert.")
ValueError: Got invalid type to convert.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GooglePhotos\DealGooglePhotosArchive.py", line 149, in <module>
    dealExif()
  File "D:\GooglePhotos\DealGooglePhotosArchive.py", line 129, in dealExif
    exif_bytes = piexif.dump(exif_dict)
  File "C:\Users\KKKK\AppData\Local\Programs\Python\Python310\lib\site-packages\piexif\_dump.py", line 68, in dump
    exif_set = _dict_to_bytes(exif_ifd, "Exif", zeroth_length)
  File "C:\Users\KKKK\AppData\Local\Programs\Python\Python310\lib\site-packages\piexif\_dump.py", line 339, in _dict_to_bytes
    raise ValueError(
ValueError: "dump" got wrong type of exif value.
41729 in Exif IFD. Got as <class 'int'>.

**Comment by Yuuuu9658** [comment]
这个可能是因为你的exif的元数据格式跟我这里不一样了，导致处理exif数据格式出错，需要你排查下

**Comment by Hkkai** [comment]
您好 想詢問 安裝完 Python 那些相關套件後  運行程式  程式內容只需要更改 最後目的地嗎?  因為我執行下來 他只會跑出最後印出的結果 可是實際上並沒有其他做動

**Comment by Yuuuu9658** [comment]
是的
